<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Sonaar.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */
function sonaar_child_enqueue_styles() {
    wp_enqueue_style( 'sonaar-child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( 'iron-master' ),
        wp_get_theme()->get('Version')
    );
}

add_action(  'wp_enqueue_scripts', 'sonaar_child_enqueue_styles' );

// add custom layout to wordpress
function sonaar_child_custom_layouts( $layouts ) {
    $layouts['sonaar-child'] = array(
        'name' => 'Sonaar Child',
        'description' => 'A custom layout for the Sonaar child theme.',
        'template' => 'sonaar-child-template.php',
    );
    return $layouts;
}

add_filter( 'theme_layouts', 'sonaar_child_custom_layouts' );

// new custom functions for the child theme
$page_concerts_landing = get_stylesheet_directory() . '/page-concerts-landing.php';
$eb_sdk = get_stylesheet_directory() . '/EB-SDK.php';

if (file_exists($page_concerts_landing)) {
    require_once $page_concerts_landing;
}
if (file_exists($eb_sdk)) {
    require_once $eb_sdk;
}